### ISSUE TITLE
Invalid API endpoint for fetching gas estimate

### ISSUE THREAD

**Issue by Tranquil-Flow** [Montoya/gas-fee-snap#56] opened 2023-01-27 03:48 UTC
Currently the readme advises to use: https://www.etherchain.org/api/gasPriceOracle which is no longer available and gives an 'unable to fetch' error. Recommend using https://beaconcha.in/api/v1/execution/gasnow, which is where you are redirected if navigating to https://etherchain.org/api/gasnow on browser.

**Comment by yashgoel72** [comment] 2023-01-29 07:14
The issue is fixed now

**Closed as completed** 2023-01-29 19:18 UTC
